targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        generate_for:
          - lib/**/*.dart
      freezed:freezed:
        generate_for:
          - lib/**/*.dart
      json_serializable:json_serializable:
        generate_for:
          - lib/**/*.dart